const MOVE_COST = 50;
module.exports.MOVE_COST = MOVE_COST;

const CARRY_COST = 50;
module.exports.CARRY_COST = CARRY_COST;

const WORK_COST = 100;
module.exports.WORK_COST = WORK_COST;

const MINIMUM_LABORER_COST = CARRY_COST + WORK_COST + MOVE_COST;
module.exports.MINIMUM_LABORER_COST = MINIMUM_LABORER_COST;